blank_issues_enabled: false
contact_links:
  - name: ⚠️ Application issue
    url: https://github.com/miru-project/miru-app/issues/new
    about: Issues and requests about the app itself should be opened in the Miru repository instead
